[project]
name = "infomads-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fire>=0.7.1",
    "matplotlib>=3.9.4",
    "scipy>=1.13.1",
    "tqdm>=4.67.1",
]
